### ISSUE TITLE
[DOCS] Add PR & Issue Templates

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/eye-controlled-mouse#1]
Add the following:

[Issue Templates](https://github.com/KendallDoesCoding/mogul-christmas/tree/main/.github/ISSUE_TEMPLATE) - Basic Issue Templates
[PR Template](https://github.com/codyseibert/fire-stone-hosting/blob/master/.github/pull_request_template.md) - Fallback PR Template

**Comment by hasnainmakada-99** [comment]
Hey @KendallDoesCoding I would like to work on this issue if you don't mind

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding I would like to work on this issue if you don't mind

Sure!

**Comment by KendallDoesCoding** [comment]
fixed in #2

**Comment by hasnainmakada-99** [comment]
> fixed in #2

Youre welcome
